apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    release: beta
    type: poc
spec:
  replicas: 3
  selector:
    matchLabels: 
      type: poc
  template:
    metadata:
      labels:
        release: beta
        type: poc
      name: helloworld-pod
    spec:
      containers:
       - name: helloworld-container
         image: "shtlamrut/hello-world-node:v1"
         ports: 
          - containerPort: 8080
          
          
         
   ---
   
   apiVersion: v1
   kind: Service
   metadata:
     name: helloworld-service
   spec:
     type: NodePort
     ports:
        - targetPort: 8080
          port: 80
          nodePort: 30001
     selector:
        release: beta
        type: poc
