apiVersion: v1
kind: Pod
spec:
  containers:
    - name: tools
      image: nekottyo/kustomize-kubeval
      command:
        - cat
      tty: true  
    - name: docker
      image: docker:latest
      command:
        - cat
      tty: true
      privileged: true
      volumeMounts:
       - name: dockersock
         mountPath: /var/run/docker.sock  
       - name: sharedvolume
         mountPath: /root/.docker   
         
    - name: kubectl
      image: bitnami/kubectl
      command:
        - cat
      tty: true
      privileged: true 
      volumeMounts:
       - name: dockersock
         mountPath: /var/run/docker.sock  
       - name: sharedvolume
         mountPath: /root/.docker   
volumes:
  - name: docker-sock
    hostPath:
    path: /var/run/docker.sock 
