apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kubectl
    image: bitnami/kubectl
    command:
    - cat
    tty: true
  - name: docker
    image: docker:19.03.1
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
    - name: sharedvolume
      mountPath: /root/.docker   
volumes:
  - name: docker-sock
    hostPath:
    path: /var/run/docker.sock 
